spring:
  application:
    name: crud-tracker
  mvc:
    problemdetails:
      enabled: true
    api-version:
      use:
        path-segment: 1
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      lifecycle-management: start-only
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5332/ExpenseTracker
    username: ${POSTGRES_DB_NAME}
    password: ${POSTGRES_DB_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    docExpansion: none
    displayRequestDuration: true
  packages-to-scan:
    - com.expense.tracker.crudtracker.controller
    - com.expense.tracker.crudtracker.apidoc
  paths-to-match:
    - /api/**
  writer-with-default-pretty-printer: true
  show-actuator: true

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
